### ISSUE TITLE
RuntimeError: No CUDA GPUs are available

### ISSUE THREAD

**Issue by haoqing12** [yourh/DeepMHCII#2]
hi，I'm trying to use this tools, but I met this error.

 ~/DeepMHCII-master  python main.py -d configure/data.yaml -m configure/deepmhcii.yaml                         
[I 230417 23:50:38 main:65] Model Name: DeepMHCII
Traceback (most recent call last):
  File "/home/haoq/DeepMHCII-master/main.py", line 160, in <module>
    main()
  File "/home/haoq/anaconda3/envs/DeepMHCII/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/haoq/anaconda3/envs/DeepMHCII/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/haoq/anaconda3/envs/DeepMHCII/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/haoq/anaconda3/envs/DeepMHCII/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/haoq/DeepMHCII-master/main.py", line 81, in main
    model = Model(DeepMHCII, model_path=model_path.with_stem(f'{model_path.stem}-{model_id}'),
  File "/home/haoq/DeepMHCII-master/deepmhcii/models.py", line 28, in __init__
    self.model = self.network = network(**kwargs).cuda()
  File "/home/haoq/anaconda3/envs/DeepMHCII/lib/python3.9/site-packages/torch/nn/modules/module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/haoq/anaconda3/envs/DeepMHCII/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/haoq/anaconda3/envs/DeepMHCII/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/haoq/anaconda3/envs/DeepMHCII/lib/python3.9/site-packages/torch/nn/modules/module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/haoq/anaconda3/envs/DeepMHCII/lib/python3.9/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

Does this tool have to run on a computer with GPU?

**Comment by yourh** [comment]
Yes, or you need to delete all `.cuda()` in the codes.
